language: php
php:
  - '7.1'
  - '7.2'
  - nightly
sudo: false
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
install:
  - phpenv config-rm xdebug.ini || echo "xdebug is not installed"
  - travis_retry composer self-update && composer --version
before_script:
  - cd dmirogin/fakemodel
script:
  - ./vendor/bin/phpunit
